### ISSUE TITLE
When is the expected release date or release window of VideoControlNet?

### ISSUE THREAD

**Issue by TruthSearcher** [ZhihaoHu/VideoControlNet#2]
The prospect of exploring the project has me quite excited. Could you kindly inform me about the expected code release date and related materials?

Witnessing the practical workings of your VideoControlNet framework is something I'm genuinely curious about and excited to try.

**Comment by MasterHow** [comment]
+1

**Comment by Damarcreative** [comment]
> The prospect of exploring the project has me quite excited. Could you kindly inform me about the expected code release date and related materials?
> 
> Witnessing the practical workings of your VideoControlNet framework is something I'm genuinely curious about and excited to try.

Try this
https://github.com/Damarcreative/CNET-Motion

**Comment by TruthSearcher** [comment]
> > The prospect of exploring the project has me quite excited. Could you kindly inform me about the expected code release date and related materials?
> > Witnessing the practical workings of your VideoControlNet framework is something I'm genuinely curious about and excited to try.
> 
> Try this https://github.com/Damarcreative/CNET-Motion

That seems a bit too flickery for me.

**Comment by olliacc** [comment]
is there no expected release for the code?

**Comment by TruthSearcher** [comment]
@ZhihaoHu
